name: "gqmqtt"
description: "USB serial to MQTT bridge for GQ GMC-500+ Geiger Counter"
version: "1.0.0"
slug: "gqmqtt"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  port: "/dev/ttyUSB0"
  baud_rate: 115200
  model: "GMC-500+"
  mqtt_topic: "tele/geiger/cpm"
  mqtt_uri: "tcp://localhost:1883"
  mqtt_interval: 60
  mqtt_username: ""
  mqtt_password: ""
schema:
  port: str
  baudrate: int
  model: str
  mqtt_topic: str
  mqtt_uri: str
  mqtt_interval: int
  mqtt_username: str
  mqtt_password: str
init: false
startup: once
uart: true
host_network: true
video: false
homeassistant_api: false
hassio_api: false
